# Ux500 Platform Support

ifdef CONFIG_UX500_SOC_DBX500
snd-soc-ux500-platform-objs := ux500_pcm.o ux500_msp_dai.o ux500_msp_i2s.o
obj-y += snd-soc-ux500-platform.o
endif

obj-y += snd-soc-ux500-machine.o

ifdef CONFIG_UX500_SOC_DB8500
snd-soc-u8500-objs := u8500.o
obj-y += snd-soc-u8500.o
endif


